name: "CI"

on:
  create:
    tags:
      - "v*"

  workflow_dispatch:

jobs:
  build-images:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Find Release version"
        id: "find_release_version"
        run: "echo \"::set-output name=release_version::${GITHUB_REF#refs/tags/}\""
      - name: "Login to GitHub Container Registry"
        uses: "docker/login-action@v1"
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.CR_PAT }}"
      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v1"
      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v1"
      - name: "Build and push Image"
        id: "build_push_image"
        uses: "docker/build-push-action@v2"
        env:
          RELEASE_VERSION: "${{ steps.find_release_version.outputs.release_version }}"
        with:
          file: "Dockerfile"
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.RELEASE_VERSION }}

